services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB:       wallet_db
      POSTGRES_USER:     wallet_user
      POSTGRES_PASSWORD: wallet_password
    ports:
      - "6543:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wallet_user", "-d", "wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - config.env  
    environment:
      DB_HOST: db
      DB_PORT: "5432"
    ports:
      - "8080:8080" 
    restart: unless-stopped

volumes:
  db_data:
